# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 魔力叉烧包! Eleanor Mao
headtitle: 魔力叉烧包!
subtitle: 您的好友魔力叉烧包已上线
description: 您的好友魔力叉烧包已上线~_(┐「ε:)_❤
author: Eleanor Mao
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://eleanormao.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
demo_dir: demo
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: diary
category_map:
tag_map:
home_posts_tag: true # show posts tags

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
#theme: cactus-dark
theme: beantech

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:EleanorMao/eleanormao.github.io.git
  branch: master

search:
  path: search.json
  field: all

marked:
  gfm: true
  breaks: false

# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'


#Custom Setting Start

# Site settings
SEOTitle: 魔力叉烧包
email: danningmao@outlook.com
keyword: ""
header-img: img/header_img/home.JPG
signature: false #show signature
signature-img: img/signature/BeanTechSign-white.png

# SNS settings
# RSS: false
weibo_username: 1700934972/profile?rightmod=1&wvr=6&mod=personinfo&is_all=1
# zhihu_username:     Demonbane
github_username: EleanorMao
twitter_username: eleanormao
#facebook_username:  YenYuHsuan
#linkedin_username:  yu-hsuan-yen

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Duoshuo settings
disqus_username: www-chashaobao-net
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: false                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 6b4134eecce4a9849b989a2d36031acf
# Google Analytics
#ga_track_id: 'UA-XXXXXXXX-X'          # Format: UA-xxxxxx-xx
#ga_domain: www.chashaobao.net


# Sidebar settings
sidebar: true                       # whether or not using Sidebar.
sidebar-about-description: "为自己的人生寻找意义"
sidebar-avatar: img/me.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- short-about
- featured-tags
- projects
- recent-posts
- archive
#- friends-blog

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true


## Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


## Friends
friends: [{
  title: "No Friend",
  href: "#"
}]

projects: [
  {
    "name": "asumi-ui",
    "url": "https://github.com/EleanorMao/asumi-ui",
    "desc": "A light react ui library"
  },
  {
    "name": "asumi-theme-generator",
    "url": "https://github.com/EleanorMao/asumi-theme-generator",
    "desc": "asumi theme generator"
  },
  {
    "name": "asumi-cli",
    "url": "https://github.com/asumi-ui/asumi-cli",
    "desc": "scaffolding tool for asumi ui(react)"
  },
  {
    "name": "React-TreeTable",
    "url": "https://github.com/EleanorMao/React-TreeTable",
    "desc": "An easy react table component render tree structure and merge cells"
  },
  {
    "name": "React-Scroll",
    "url": "https://github.com/EleanorMao/React-Scroll",
    "desc": "Scroll by gesture"
  }
]

#Custom Setting End

html_minifier:
  enable: true
  ignore_error: false
  exclude:

css_minifier:
  enable: true
  exclude:
      - '*.min.css'

js_minifier:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'

image_minifier:
  enable: true
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false